"""One-off generator for ``src/client/fixtures/empty.xlsx``.

Not part of the runtime image (``openpyxl`` is a *dev*-only dependency — see ``pyproject.toml``).
Run manually whenever the fixture needs regenerating:

    uv run python scripts/generate_empty_workbook_fixture.py

Produces a minimal, valid ``.xlsx`` workbook with a single sheet named ``New`` (v1 parity:
``keboola.wr-onedrive`` names the sheet it auto-creates ``New`` when it uploads a brand-new
workbook for a ``workbook.path`` target that doesn't exist yet). The generated bytes are committed
to the repo (``src/client/excel_writer.py`` loads them at runtime via ``importlib.resources`` —
see its ``_load_empty_workbook`` helper) so the runtime image never needs ``openpyxl`` installed.
"""

from pathlib import Path

from openpyxl import Workbook

FIXTURE_PATH = Path(__file__).resolve().parent.parent / "src" / "client" / "fixtures" / "empty.xlsx"


def main() -> None:
    workbook = Workbook()
    workbook.active.title = "New"
    workbook.save(FIXTURE_PATH)
    print(f"Wrote {FIXTURE_PATH} ({FIXTURE_PATH.stat().st_size} bytes).")


if __name__ == "__main__":
    main()
