"""Excel worksheet writer for keboola.wr-onedrive-v2 (mode=table_excel).

Design spec: ``docs/superpowers/specs/2026-08-17-wr-onedrive-v2-design.md`` §4 (Excel rows of the
capability table + "Excel session" mechanics) and §5 (Excel options). This is a port of
``keboola.wr-onedrive`` (v1, PHP)'s ``InsertRowsManager``/workbook-resolution semantics — v1
feature parity is an acceptance criterion, so the row-by-row write algorithm, header-skip rules,
and path-targeting forms below intentionally mirror v1's behavior rather than inventing new ones.

Three concerns live here, as module-level functions taking an injected
:class:`~client.graph_client.GraphClient` (same style as ``client.drives``/``client.uploader``):

- **Workbook resolution** (:func:`resolve_workbook`) — targets a workbook by ``driveId``+
  ``fileId``, a ``/root-relative`` path, a ``drive://``/``site://`` path, or an ``https://``
  sharing link; creates a minimal empty workbook when a path-mode target doesn't exist yet.
- **Session lifecycle** (:func:`workbook_session`) — a context manager wrapping Excel's
  ``createSession``/``closeSession`` dance, with 202-polling and a sessionless fallback (Graph
  guarantees persistence either way; a session is a performance optimization only).
- **Worksheet resolution + write** (:func:`resolve_worksheet`, :func:`write_table`) — finds/
  creates/renames the target sheet, then writes a CSV into it in batched ``range`` PATCHes,
  reproducing v1's overwrite (clear + write from A1) and append (usedRange-offset, header-skip)
  semantics, plus a third, non-v1 ``write_mode``: upsert (key-column matching, in-place row
  updates — see :func:`_write_upsert`).

Callers (plan Task 8's Excel-mode ``run()`` wiring) are expected to: call
:func:`resolve_workbook` once, open :func:`workbook_session` around the rest of the row, call
:func:`resolve_worksheet` inside it, then :func:`write_table`. Writes are always serialized (no
concurrency anywhere in this module) — Microsoft's own guidance for one workbook.
"""

import base64
import csv
import itertools
import logging
import re
import time
from collections.abc import Iterator
from contextlib import contextmanager
from dataclasses import dataclass
from importlib import resources
from typing import Any
from urllib.parse import quote, unquote

from client.exceptions import (
    GraphClientError,
    GraphNotFoundError,
    InvalidWorkbookFormatError,
    InvalidWorkbookPathError,
    KeyColumnNotFoundError,
    MultipleSitesFoundError,
    UpsertRangeTooLargeError,
    WorkbookNotFoundError,
    WorksheetNotFoundError,
)
from client.graph_client import GraphClient
from client.headers import normalize_header_row
from client.uploader import encode_path_segments, ensure_folder, upload_file, validate_path
from configuration import Account, AccountType, Workbook, Worksheet, WriteMode

logger = logging.getLogger(__name__)

# The one and only content type Excel mode ever writes; anything else at the resolved path/ids
# target is a user configuration error (design spec §6 "non-XLSX workbook target").
XLSX_MIME_TYPE = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"

# `$select` used for every workbook-item lookup (ids mode, every path form, the sharing-link
# driveItem) — just enough to identify the item, check its mime type, and (for creation) know
# where it lives.
WORKBOOK_ITEM_SELECT = "id,name,file,parentReference"

# `$select` used when listing worksheets (`resolve_worksheet`) — `visibility` isn't consumed in
# this module, but is needed by plan Task 8's `getWorksheets` sync action (v1-parity output
# includes hidden sheets with a `" (hidden)"` title suffix).
WORKSHEET_LIST_SELECT = "id,name,position,visibility"

# How often to poll the `Location` header of a 202 `createSession` response (design spec §4:
# "`202`/`Location` polling").
_SESSION_POLL_INTERVAL_SECONDS = 2.0

# Deadline for `_poll_session_creation`: `_SESSION_POLL_MAX_ATTEMPTS * _SESSION_POLL_INTERVAL_SECONDS`
# ~= 120s. A session that's still "running" past this point falls back to sessionless (same as any
# other session-creation failure) rather than polling forever.
_SESSION_POLL_MAX_ATTEMPTS = 60

# Bundled minimal-XLSX fixture (generated by `tests/setup/generate_empty_workbook_fixture.py`),
# loaded via `importlib.resources` so the runtime image never needs `openpyxl` installed (it's a
# dev-only dependency — see `pyproject.toml`).
_EMPTY_WORKBOOK_PACKAGE = "client.fixtures"
_EMPTY_WORKBOOK_RESOURCE_NAME = "empty.xlsx"

# v1's `workbook.path` forms, matched in this order in `_resolve_by_path`: an `https://` sharing
# link and the `drive://`/`site://` forms each have a distinct, unambiguous prefix; the plain
# root-relative form is "starts with a single `/`" and is checked last so it never shadows the
# others. Anything matching none of these four is `InvalidWorkbookPathError` ("unexpected path
# format").
_SHARING_LINK_RE = re.compile(r"^https://", re.IGNORECASE)
_DRIVE_PATH_RE = re.compile(r"^drive://([^/]+)/(.+)$")
_SITE_PATH_RE = re.compile(r"^site://([^/]+)/(.+)$")
_ROOT_PATH_RE = re.compile(r"^/(.+)$")

# A single spreadsheet cell address, e.g. "C9" -> column "C", row 9.
_CELL_ADDRESS_RE = re.compile(r"^([A-Za-z]+)(\d+)$")

# `write_mode='upsert'` guardrail: above this many cells in the existing used range, refuse the
# combined `usedRange` read up front rather than attempting it — well below Graph's own hard
# 5,000,000-cell read limit, but already impractical to hold in memory and diff row-by-row for a
# component that's meant to run unattended. 'overwrite'/'append' never read the existing sheet's
# values at all, so they remain the escape hatch a oversized-sheet row should fall back to.
_UPSERT_MAX_EXISTING_CELLS = 500_000

# Joins composite key column values into one lookup string (`_build_key_columns_index`). A NUL
# byte never appears in a CSV cell value, so this can't collide with a genuine multi-column key
# that happens to contain the separator itself.
_KEY_SEPARATOR = "\x00"


# ---------------------------------------------------------------------------------------------
# Column / range address math
# ---------------------------------------------------------------------------------------------


def column_int_to_str(column: int) -> str:
    """Convert a 1-based column number to its spreadsheet letter(s): 1 -> "A", 27 -> "AA"."""
    if column < 1:
        raise ValueError(f"Column number must be >= 1, got {column}.")
    letters = ""
    while column > 0:
        column, remainder = divmod(column - 1, 26)
        letters = chr(ord("A") + remainder) + letters
    return letters


def column_str_to_int(column: str) -> int:
    """Convert spreadsheet column letter(s) to a 1-based column number: "A" -> 1, "AA" -> 27."""
    if not column or not column.isalpha():
        raise ValueError(f"Invalid column letters: {column!r}.")
    result = 0
    for char in column.upper():
        result = result * 26 + (ord(char) - ord("A") + 1)
    return result


@dataclass(frozen=True)
class RangeAddress:
    """A parsed Excel range address, e.g. "Sheet1!C9:F20" -> sheet="Sheet1", C9..F20."""

    sheet: str
    start_col: int
    start_row: int
    end_col: int
    end_row: int


def parse_range_address(address: str) -> RangeAddress:
    """Parse a Graph range ``address`` string (``"Sheet1!C9:F20"`` or a bare ``"A1:A1"``)."""
    sheet, _, cells = address.partition("!")
    if not cells:
        sheet, cells = "", sheet
    start_cell, separator, end_cell = cells.partition(":")
    if not separator:
        end_cell = start_cell

    start_match = _CELL_ADDRESS_RE.match(start_cell)
    end_match = _CELL_ADDRESS_RE.match(end_cell)
    if not start_match or not end_match:
        raise ValueError(f"Cannot parse range address {address!r}.")

    return RangeAddress(
        sheet=sheet,
        start_col=column_str_to_int(start_match.group(1)),
        start_row=int(start_match.group(2)),
        end_col=column_str_to_int(end_match.group(1)),
        end_row=int(end_match.group(2)),
    )


def _format_range_address(start_col: int, start_row: int, end_col: int, end_row: int) -> str:
    """Build a bare (no sheet prefix) range address for a per-worksheet ``range(address=...)`` call."""
    return f"{column_int_to_str(start_col)}{start_row}:{column_int_to_str(end_col)}{end_row}"


# ---------------------------------------------------------------------------------------------
# Workbook resolution
# ---------------------------------------------------------------------------------------------


def resolve_workbook(
    client: GraphClient, account: Account, workbook: Workbook, *, create_if_missing: bool = True
) -> tuple[str, str, bool]:
    """Resolve ``workbook`` to a concrete ``(drive_id, file_id, created)``.

    ``created`` is ``True`` only when a path-mode target didn't exist yet and a minimal empty
    workbook was uploaded in its place (never for ``driveId``+``fileId`` or sharing-link
    targeting — see :func:`_resolve_by_ids` / :func:`_fetch_sharing_link_item`).

    ``create_if_missing`` (default ``True``, matching row-run Excel mode and the
    ``createWorkbook`` sync action) controls what happens when a path-mode target doesn't exist:
    when ``False`` (plan Task 8's ``getWorksheets``/``createWorksheet`` sync actions), a missing
    workbook raises :class:`~client.exceptions.WorkbookNotFoundError` instead of being silently
    created — listing or adding a worksheet should never have the side effect of conjuring the
    workbook it's supposed to belong to.
    """
    if workbook.path is None:
        return _resolve_by_ids(client, workbook)
    return _resolve_by_path(client, account, workbook.path, create_if_missing=create_if_missing)


def _resolve_by_ids(client: GraphClient, workbook: Workbook) -> tuple[str, str, bool]:
    assert workbook.drive_id is not None and workbook.file_id is not None  # Workbook model's XOR
    try:
        item = client.get(
            f"/drives/{workbook.drive_id}/items/{workbook.file_id}",
            params={"$select": WORKBOOK_ITEM_SELECT},
        ).json()
    except GraphNotFoundError as exc:
        raise GraphNotFoundError(
            "Configured workbook XLSX file not found.",
            status_code=exc.status_code,
            error_code=exc.error_code,
        ) from exc
    _check_xlsx_mime(item)
    return workbook.drive_id, workbook.file_id, False


def _resolve_by_path(
    client: GraphClient, account: Account, path: str, *, create_if_missing: bool
) -> tuple[str, str, bool]:
    if _SHARING_LINK_RE.match(path):
        item = _fetch_sharing_link_item(client, path)
        return item["parentReference"]["driveId"], item["id"], False

    business = account.account_type != AccountType.PRIVATE_ONEDRIVE
    drive_id, relative_path, _prefix = _parse_workbook_path(client, path)
    return _get_or_create_workbook_item(
        client, drive_id, relative_path, business, path=path, create_if_missing=create_if_missing
    )


def _parse_workbook_path(client: GraphClient, path: str) -> tuple[str, str, list[str]]:
    """Parse a ``drive://``/``site://``/root-relative ``workbook.path`` into its API drive.

    Returns ``(drive_id, relative_path, v1_path_prefix)`` — ``v1_path_prefix`` is v1's
    :class:`~Api\\Model\\File` breadcrumb prefix for each targeting form (``[]`` for
    ``drive://``, ``["sites", siteName]`` for ``site://``, ``["my"]`` for a root-relative path),
    consumed only by :func:`search_workbook` (byte-compatible with v1's ``search`` sync action
    output — the "path" field in ``{"file": {...}}``). Sharing links are handled by the caller
    *before* this is reached (they never carry a v1 prefix, and their target drive comes from
    the resolved driveItem itself, not a ``GET /me/drive`` or ``GET /sites/{id}/drive`` call).
    """
    drive_match = _DRIVE_PATH_RE.match(path)
    site_match = _SITE_PATH_RE.match(path)
    root_match = _ROOT_PATH_RE.match(path)

    if drive_match:
        return unquote(drive_match.group(1)), drive_match.group(2), []
    if site_match:
        site_name = unquote(site_match.group(1))
        site_id = _resolve_site_id(client, site_name)
        drive_id = client.get(f"/sites/{site_id}/drive").json()["id"]
        return drive_id, site_match.group(2), ["sites", site_name]
    if root_match:
        drive_id = client.get("/me/drive").json()["id"]
        return drive_id, root_match.group(1), ["my"]
    raise InvalidWorkbookPathError(f'Unexpected path format for workbook.path: "{path}".')


def _fetch_sharing_link_item(client: GraphClient, link: str) -> dict[str, Any]:
    """Resolve an ``https://`` sharing link to its driveItem (id, name, parentReference, ...).

    v1 parity: truncates the link to 32 characters (with a trailing ``"..."`` regardless of
    whether truncation actually happened — v1's own quirk, ``substr($url, 0, 32) . '...'``) in
    the not-found/access-denied message.
    """
    encoded = _encode_sharing_link(link)
    try:
        item = client.get(f"/shares/{encoded}/driveItem", params={"$select": WORKBOOK_ITEM_SELECT}).json()
    except GraphClientError as exc:
        raise GraphNotFoundError(
            f'The sharing link "{_truncate_link(link)}" not exists, or you do not have permission '
            "to access it.",
            status_code=exc.status_code,
            error_code=exc.error_code,
        ) from exc
    _check_xlsx_mime(item)
    return item


def _truncate_link(link: str, max_length: int = 32) -> str:
    return f"{link[:max_length]}..."


def _encode_sharing_link(link: str) -> str:
    """Graph's ``u!`` base64url encoding of a sharing link, for ``/shares/{token}/driveItem``."""
    encoded = base64.b64encode(link.encode("utf-8")).decode("ascii")
    encoded = encoded.rstrip("=").replace("+", "-").replace("/", "_")
    return f"u!{encoded}"


def _resolve_site_id(client: GraphClient, site_name: str) -> str:
    results = client.get("/sites", params={"search": site_name, "$select": "id,name"}).json().get("value", [])
    if not results:
        raise GraphNotFoundError(f'SharePoint site "{site_name}" not found.')
    if len(results) > 1:
        names = ", ".join(f'"{result.get("name")}"' for result in results)
        raise MultipleSitesFoundError(
            f'Multiple sites found for "{site_name}": {names}. Use a more specific site name, or '
            "target the workbook by workbook.drive_id/workbook.file_id instead."
        )
    return results[0]["id"]


def _get_or_create_workbook_item(
    client: GraphClient, drive_id: str, relative_path: str, business: bool, *, path: str, create_if_missing: bool
) -> tuple[str, str, bool]:
    encoded_path = encode_path_segments(relative_path)
    try:
        item = client.get(
            f"/drives/{drive_id}/root:/{encoded_path}", params={"$select": WORKBOOK_ITEM_SELECT}
        ).json()
    except GraphNotFoundError as exc:
        if not create_if_missing:
            raise WorkbookNotFoundError(
                f'Workbook not found for path "{path}".', status_code=exc.status_code, error_code=exc.error_code
            ) from exc
        item = _create_empty_workbook(client, drive_id, relative_path, business)
        return drive_id, item["id"], True
    _check_xlsx_mime(item)
    return drive_id, item["id"], False


def _create_empty_workbook(client: GraphClient, drive_id: str, relative_path: str, business: bool) -> dict[str, Any]:
    folder_path, file_name = _split_folder_and_name(relative_path)
    if folder_path:
        validate_path(folder_path, business)
    parent_id = ensure_folder(client, drive_id, folder_path)
    with resources.as_file(resources.files(_EMPTY_WORKBOOK_PACKAGE).joinpath(_EMPTY_WORKBOOK_RESOURCE_NAME)) as fixture:
        item = upload_file(client, drive_id, parent_id, str(fixture), file_name, conflict_behavior="replace")
    logger.info('New workbook "%s" created.', relative_path)
    return item


def _split_folder_and_name(relative_path: str) -> tuple[str, str]:
    normalized = relative_path.strip("/")
    folder, separator, name = normalized.rpartition("/")
    return (folder if separator else ""), name


def _check_xlsx_mime(item: dict[str, Any]) -> None:
    mime_type = (item.get("file") or {}).get("mimeType")
    if mime_type != XLSX_MIME_TYPE:
        raise InvalidWorkbookFormatError(f'File is not in the "XLSX" Excel format. Mime type: "{mime_type}"')


# ---------------------------------------------------------------------------------------------
# `search` sync action (plan Task 8, design spec §5) — read-only workbook lookup by path
# ---------------------------------------------------------------------------------------------


@dataclass(frozen=True)
class WorkbookSearchResult:
    """A found workbook, shaped for the ``search`` sync action's ``{"file": {...}}`` output."""

    drive_id: str
    file_id: str
    name: str
    path: str | None


def search_workbook(client: GraphClient, account: Account, path: str) -> WorkbookSearchResult | None:
    """Resolve ``path`` to an existing workbook without ever creating one (v1's ``search`` action).

    Returns ``None`` when a ``drive://``/``site://``/root-relative path is well-formed but no
    item exists there (the sync action's ``{"file": null}`` shape) — an unrecognized path format
    still raises :class:`~client.exceptions.InvalidWorkbookPathError`, and an inaccessible/
    nonexistent ``https://`` sharing link still raises (v1 parity: a bad sharing link is always a
    configuration error, never a silent "not found").
    """
    if _SHARING_LINK_RE.match(path):
        item = _fetch_sharing_link_item(client, path)
        return WorkbookSearchResult(
            drive_id=item["parentReference"]["driveId"],
            file_id=item["id"],
            name=item["name"],
            path=_format_path_segments(item, []),
        )

    drive_id, relative_path, prefix = _parse_workbook_path(client, path)
    encoded_path = encode_path_segments(relative_path)
    try:
        item = client.get(
            f"/drives/{drive_id}/root:/{encoded_path}", params={"$select": WORKBOOK_ITEM_SELECT}
        ).json()
    except GraphNotFoundError:
        return None
    _check_xlsx_mime(item)
    return WorkbookSearchResult(
        drive_id=drive_id, file_id=item["id"], name=item["name"], path=_format_path_segments(item, prefix)
    )


def _format_path_segments(item: dict[str, Any], prefix: list[str]) -> str | None:
    """v1's ``File::from``/``jsonSerialize`` "path" breadcrumb: ``prefix`` + parent folder segments.

    ``item["parentReference"]["path"]`` is Graph's ``"/drives/{id}/root:/folder/sub"``-style
    string (present only when the item isn't at the drive root); v1 takes everything after the
    literal ``"root:/"`` marker and explodes it on ``/`` — no percent-decoding, matched here for
    byte parity. ``None`` (not ``""``) when there are no segments at all (v1:
    ``$this->path ? implode('/', $this->path) : null``).
    """
    segments = list(prefix)
    parent_path = (item.get("parentReference") or {}).get("path")
    if parent_path and "root:/" in parent_path:
        after_root = parent_path.split("root:/", 1)[1]
        if after_root:
            segments.extend(after_root.split("/"))
    return "/".join(segments) if segments else None


# ---------------------------------------------------------------------------------------------
# Workbook session lifecycle
# ---------------------------------------------------------------------------------------------


def _session_header(session_id: str | None) -> dict[str, str]:
    return {"workbook-session-id": session_id} if session_id is not None else {}


@contextmanager
def workbook_session(client: GraphClient, drive_id: str, file_id: str) -> Iterator[str | None]:
    """Open an Excel workbook session for the duration of the ``with`` block.

    Yields the session id (for the caller to pass into :func:`resolve_worksheet`/
    :func:`write_table`), or ``None`` when the session couldn't be created — Graph still
    guarantees write persistence without one, so sessionless is a valid (if slower) fallback
    rather than an error (design spec §4). ``closeSession`` always runs in ``finally``,
    exceptions swallowed (v1 relied on a PHP destructor for this; a `finally` block is the
    equivalent here without the destructor timing pitfalls).
    """
    session_id = _create_session(client, drive_id, file_id)
    try:
        yield session_id
    finally:
        if session_id is not None:
            _close_session(client, drive_id, file_id, session_id)


def _create_session(client: GraphClient, drive_id: str, file_id: str) -> str | None:
    url = f"/drives/{drive_id}/items/{file_id}/workbook/createSession"
    try:
        response = client.post(
            url,
            json={"persistChanges": True},
            headers={"Prefer": "respond-async"},
            retry_transient_workbook=True,
        )
    except GraphClientError:
        logger.warning("The workbook session could not be created.")
        return None

    if response.status_code == 201:
        return response.json()["id"]
    if response.status_code == 202:
        return _poll_session_creation(client, response.headers.get("Location"))
    logger.warning("The workbook session could not be created.")
    return None


def _poll_session_creation(client: GraphClient, location: str | None) -> str | None:
    """Poll ``location`` (a 202 ``createSession``'s ``Location`` header) up to a deadline.

    Bounded to :data:`_SESSION_POLL_MAX_ATTEMPTS` (~120s at :data:`_SESSION_POLL_INTERVAL_SECONDS`
    intervals) so a session stuck "running" doesn't poll forever; a timed-out poll falls back to
    sessionless the same way any other session-creation failure does (design spec §4 — a session
    is a performance optimization only, never required for correctness).
    """
    if location:
        try:
            for _ in range(_SESSION_POLL_MAX_ATTEMPTS):
                body = client.get(location, absolute=True).json()
                status = body.get("status")
                if status == "running":
                    time.sleep(_SESSION_POLL_INTERVAL_SECONDS)
                    continue
                if status == "succeeded" and body.get("resourceLocation"):
                    result = client.get(body["resourceLocation"], absolute=True).json()
                    return result.get("id")
                break
        except GraphClientError:
            pass
    logger.warning("The workbook session could not be created.")
    return None


def _close_session(client: GraphClient, drive_id: str, file_id: str, session_id: str) -> None:
    url = f"/drives/{drive_id}/items/{file_id}/workbook/closeSession"
    try:
        client.post(url, headers=_session_header(session_id), retry_transient_workbook=True)
    except Exception:
        logger.debug("Failed to close workbook session %s; ignoring.", session_id, exc_info=True)


# ---------------------------------------------------------------------------------------------
# Worksheet resolution
# ---------------------------------------------------------------------------------------------


def _worksheet_base_url(drive_id: str, file_id: str, worksheet_id: str) -> str:
    # Worksheet ids contain `{}` (e.g. "{00000000-0001-0000-0000-000000000000}"), which must be
    # percent-encoded (-> %7B / %7D) to be a valid URL path segment.
    encoded_id = quote(worksheet_id, safe="")
    return f"/drives/{drive_id}/items/{file_id}/workbook/worksheets/{encoded_id}"


def _list_worksheets(client: GraphClient, drive_id: str, file_id: str, headers: dict[str, Any]) -> list[dict[str, Any]]:
    """Page through every worksheet in the workbook (``@odata.nextLink``, workbook-transient retries).

    Delegates to :meth:`GraphClient.get_paged` (its ``**request_kwargs`` passthrough is what makes
    ``retry_transient_workbook=True`` possible here) instead of hand-rolling the same pagination
    loop again (phase 8 audit).
    """
    url = f"/drives/{drive_id}/items/{file_id}/workbook/worksheets"
    return list(
        client.get_paged(
            url, params={"$select": WORKSHEET_LIST_SELECT}, headers=headers, retry_transient_workbook=True
        )
    )


def resolve_worksheet(
    client: GraphClient, drive_id: str, file_id: str, worksheet: Worksheet, session: str | None
) -> tuple[str, bool, str]:
    """Resolve ``worksheet`` to ``(worksheet_id, is_new, actual_name)``, creating/renaming as needed.

    Targeting (``Worksheet``'s ``id``/``position``/``name`` are validated mutually-exclusive-ish
    by the config model — see ``configuration.Worksheet``): ``id``/``position`` must match an
    existing sheet (:class:`~client.exceptions.WorksheetNotFoundError` otherwise, v1 parity — no
    create-by-id/position); a bare ``name`` creates the sheet when missing. Either way, a
    ``name`` that differs from the resolved sheet's actual name triggers a rename *before* the
    caller writes anything (v1 parity: "worksheet.id/position + worksheet.name" = "target this
    sheet, and also rename it").
    """
    headers = _session_header(session)
    worksheets = _list_worksheets(client, drive_id, file_id, headers)

    if worksheet.id is not None:
        match = _find_worksheet(worksheets, lambda item: item["id"] == worksheet.id)
        if match is None:
            raise WorksheetNotFoundError(f'Worksheet with id "{worksheet.id}" not found in the workbook.')
        worksheet_id, actual_name, is_new = match["id"], match["name"], False
    elif worksheet.position is not None:
        match = _find_worksheet(worksheets, lambda item: item["position"] == worksheet.position)
        if match is None:
            raise WorksheetNotFoundError(f'Worksheet at position {worksheet.position} not found in the workbook.')
        worksheet_id, actual_name, is_new = match["id"], match["name"], False
    else:
        # `configuration.Worksheet` requires at least one of id/name/position; having reached
        # here (no id, no position), `name` must be set.
        assert worksheet.name is not None
        match = _find_worksheet(worksheets, lambda item: item["name"] == worksheet.name)
        if match is not None:
            worksheet_id, actual_name, is_new = match["id"], match["name"], False
        else:
            created = _create_worksheet(client, drive_id, file_id, worksheet.name, headers)
            worksheet_id, actual_name, is_new = created["id"], created["name"], True

    if worksheet.name and not is_new and actual_name != worksheet.name:
        _rename_worksheet(client, drive_id, file_id, worksheet_id, worksheet.name, headers)
        actual_name = worksheet.name

    return worksheet_id, is_new, actual_name


def _find_worksheet(worksheets: list[dict[str, Any]], predicate) -> dict[str, Any] | None:
    return next((item for item in worksheets if predicate(item)), None)


def _create_worksheet(client: GraphClient, drive_id: str, file_id: str, name: str, headers: dict[str, Any]) -> dict[str, Any]:
    url = f"/drives/{drive_id}/items/{file_id}/workbook/worksheets/add"
    response = client.post(url, json={"name": name}, headers=headers, retry_transient_workbook=True)
    logger.info('New sheet "%s" created.', name)
    return response.json()


def _rename_worksheet(
    client: GraphClient, drive_id: str, file_id: str, worksheet_id: str, new_name: str, headers: dict[str, Any]
) -> None:
    url = _worksheet_base_url(drive_id, file_id, worksheet_id)
    client.patch(url, json={"name": new_name}, headers=headers, retry_transient_workbook=True)


def _read_header_row(
    client: GraphClient, drive_id: str, file_id: str, worksheet_id: str, headers: dict[str, Any]
) -> list[str]:
    """Read a worksheet's first-row cell values (as strings), via ``usedRange``'s row 0.

    Shared by :func:`_prepare_append` (decides whether an append target already has a header)
    and :func:`list_worksheets_with_headers` (the ``getWorksheets`` sync action's per-sheet
    ``header`` field) — both need the exact same raw cell values before applying their own,
    different, follow-up logic (a mismatch warning vs. v1's ASCII normalization).

    Graph still returns a one-cell row (``text: [[""]]``) for a genuinely empty worksheet rather
    than erroring, so this never raises for "no data yet" — callers see ``[""]``, not ``[]``, and
    decide for themselves what "empty" means for their purpose.
    """
    base_url = _worksheet_base_url(drive_id, file_id, worksheet_id)
    header_row = client.get(
        f"{base_url}/range/usedRange(valuesOnly=true)/row(row=0)",
        params={"$select": "address,text"},
        headers=headers,
        retry_transient_workbook=True,
    ).json()
    text_rows = header_row.get("text") or []
    return [str(cell) for cell in text_rows[0]] if text_rows else []


def list_worksheets(client: GraphClient, drive_id: str, file_id: str) -> list[dict[str, Any]]:
    """List a workbook's worksheets (``id``/``name``/``position``/``visibility``), position-sorted.

    Sessionless (sync actions never open a workbook session — v1 doesn't either). This is the
    lightweight half of :func:`list_worksheets_with_headers` (no per-sheet header read) — shared
    by the ``listWorksheets`` sync action (workbook/worksheet dropdown UX addition), which only
    needs enough to build a ``SelectElement`` per sheet, never the header row.
    """
    worksheets = _list_worksheets(client, drive_id, file_id, headers={})
    worksheets.sort(key=lambda item: item["position"])
    return worksheets


def list_worksheets_with_headers(client: GraphClient, drive_id: str, file_id: str) -> list[dict[str, Any]]:
    """List every worksheet in a workbook with its normalized header (``getWorksheets``, §5).

    Sessionless (sync actions never open a workbook session — v1 doesn't either) and
    position-sorted, matching v1's ``Api::getSheets`` output shape exactly (field names, ``"
    (hidden)"`` title suffix, ASCII-normalized ``header`` via :mod:`client.headers`). Built on top
    of :func:`list_worksheets` — the listing + sort is identical, this just adds the per-sheet
    header read.
    """
    worksheets = list_worksheets(client, drive_id, file_id)

    result: list[dict[str, Any]] = []
    for item in worksheets:
        header_cells = _read_header_row(client, drive_id, file_id, item["id"], headers={})
        visible = str(item.get("visibility", "")).lower() == "visible"
        name = item["name"]
        result.append(
            {
                "position": item["position"],
                "name": name,
                "title": name if visible else f"{name} (hidden)",
                "driveId": drive_id,
                "fileId": file_id,
                "worksheetId": item["id"],
                "visible": visible,
                "header": normalize_header_row(header_cells),
            }
        )
    return result


# ---------------------------------------------------------------------------------------------
# Write algorithm (port of v1's InsertRowsManager)
# ---------------------------------------------------------------------------------------------


def write_table(
    client: GraphClient,
    drive_id: str,
    file_id: str,
    worksheet_id: str,
    csv_path: str,
    *,
    write_mode: WriteMode,
    key_columns: list[str] | None = None,
    batch_size: int,
    is_new_sheet: bool,
    session: str | None,
) -> bool:
    """Stream ``csv_path`` into the worksheet, batched ``batch_size`` rows per ``range`` PATCH.

    Returns ``False`` (touching nothing on the sheet) when ``csv_path`` has no header row at all
    (a completely empty CSV) — the caller logs ``Ignored empty CSV file "<name>".`` and exits 0,
    v1 parity. Returns ``True`` otherwise.

    ``write_mode='overwrite'``: clears the whole sheet first (unless it was just created, in
    which case there's nothing to clear) and writes from A1, header included.

    ``write_mode='append'``: offsets from the sheet's ``usedRange`` — an existing non-empty
    header means the CSV's own header row is skipped (with a warning if the two headers differ,
    v1 parity — the warning is informational only, it never blocks the append); an empty sheet
    (including a freshly created one) writes the header too, same as overwrite.

    ``write_mode='upsert'``: matches existing rows to CSV rows by ``key_columns`` (required
    non-empty — enforced by ``configuration.RowConfig``, not re-checked here) and updates them in
    place, appending everything else after the last used row; see :func:`_write_upsert` for the
    algorithm. An empty (or freshly created) sheet behaves like ``overwrite``.

    For ``overwrite``/``append``, the column count is fixed from the CSV's header for every batch
    (short rows padded with empty strings, long rows truncated) — Excel's range PATCH requires a
    rectangular ``values`` array. Any cell whose value starts with ``=`` is prefixed with ``'``
    (v1 parity — formula injection safety; Excel treats a leading ``'`` as "force literal text").
    ``upsert`` applies the same padding/escaping to every row it writes (via the same
    :func:`_prepare_row` helper).

    If the workbook session expires mid-write (a workbook call 404s while a session header is
    set), the session is recreated once and the same batch is retried before giving up (the same
    guarantee ``overwrite``/``append`` already had, via :func:`_patch_batch`).
    """
    with open(csv_path, newline="", encoding="utf-8") as csv_file:
        reader = csv.reader(csv_file)
        header = next(reader, None)
        if header is None:
            return False
        header_len = len(header)

        if write_mode == WriteMode.UPSERT:
            _write_upsert(
                client,
                drive_id,
                file_id,
                worksheet_id,
                header,
                reader,
                key_columns or [],
                batch_size,
                is_new_sheet,
                _session_header(session),
                session,
            )
            return True

        if write_mode == WriteMode.APPEND:
            start_row, start_col, include_header = _prepare_append(
                client, drive_id, file_id, worksheet_id, is_new_sheet, header, _session_header(session)
            )
        else:
            start_row, start_col, include_header = _prepare_overwrite(
                client, drive_id, file_id, worksheet_id, is_new_sheet, _session_header(session)
            )

        rows = _rows_to_write(header, reader, include_header)
        session_id = session
        for batch in _batched(rows, batch_size):
            padded_batch = [_prepare_row(row, header_len) for row in batch]
            session_id = _patch_batch(
                client,
                drive_id,
                file_id,
                worksheet_id,
                start_col,
                start_row,
                header_len,
                padded_batch,
                session_id,
            )
            start_row += len(padded_batch)

    return True


def _prepare_overwrite(
    client: GraphClient, drive_id: str, file_id: str, worksheet_id: str, is_new_sheet: bool, headers: dict[str, Any]
) -> tuple[int, int, bool]:
    if not is_new_sheet:
        url = f"{_worksheet_base_url(drive_id, file_id, worksheet_id)}/range/clear"
        client.post(url, json={"applyTo": "all"}, headers=headers, retry_transient_workbook=True)
    return 1, 1, True


def _prepare_append(
    client: GraphClient,
    drive_id: str,
    file_id: str,
    worksheet_id: str,
    is_new_sheet: bool,
    csv_header: list[str],
    headers: dict[str, Any],
) -> tuple[int, int, bool]:
    if is_new_sheet:
        logger.info("Sheet is empty.")
        return 1, 1, True

    base_url = _worksheet_base_url(drive_id, file_id, worksheet_id)
    used_range = client.get(
        f"{base_url}/range/usedRange(valuesOnly=true)", params={"$select": "address"}, headers=headers,
        retry_transient_workbook=True,
    ).json()
    range_info = parse_range_address(used_range["address"])

    existing_header = _read_header_row(client, drive_id, file_id, worksheet_id, headers)

    if not any(cell.strip() for cell in existing_header):
        logger.info("Sheet is empty.")
        return 1, 1, True

    if existing_header != csv_header:
        logger.warning("Headers mismatch. Ignored new header: %s", ", ".join(csv_header))

    return range_info.end_row + 1, range_info.start_col, False


def _rows_to_write(header: list[str], reader: Iterator[list[str]], include_header: bool) -> Iterator[list[str]]:
    if include_header:
        yield header
    yield from reader


def _batched(rows: Iterator[list[str]], size: int) -> Iterator[list[list[str]]]:
    iterator = iter(rows)
    while True:
        batch = list(itertools.islice(iterator, size))
        if not batch:
            return
        yield batch


def _prepare_row(row: list[str], header_len: int) -> list[str]:
    padded = list(row[:header_len]) + [""] * max(0, header_len - len(row))
    return [_escape_formula(str(cell)) for cell in padded]


def _escape_formula(value: str) -> str:
    return f"'{value}" if value.startswith("=") else value


def _patch_batch(
    client: GraphClient,
    drive_id: str,
    file_id: str,
    worksheet_id: str,
    start_col: int,
    start_row: int,
    header_len: int,
    batch: list[list[str]],
    session_id: str | None,
) -> str | None:
    end_row = start_row + len(batch) - 1
    end_col = start_col + header_len - 1
    address = _format_range_address(start_col, start_row, end_col, end_row)
    url = f"{_worksheet_base_url(drive_id, file_id, worksheet_id)}/range(address='{address}')"

    try:
        client.patch(
            url, json={"values": batch}, headers=_session_header(session_id), retry_transient_workbook=True
        )
    except GraphNotFoundError:
        if session_id is None:
            raise
        logger.info("Workbook session expired mid-write; recreating it once and retrying the batch.")
        session_id = _create_session(client, drive_id, file_id)
        client.patch(
            url, json={"values": batch}, headers=_session_header(session_id), retry_transient_workbook=True
        )

    logger.info("Inserted %d rows.", len(batch))
    return session_id


# ---------------------------------------------------------------------------------------------
# Write algorithm — upsert (write_mode='upsert')
# ---------------------------------------------------------------------------------------------


def _normalize_column_name(name: str) -> str:
    """Case/whitespace-insensitive column-name comparison for upsert's header matching.

    Deliberately not :func:`client.headers.normalize_header_row`/:func:`~client.headers.to_ascii`
    — those exist to build v1-parity ASCII-folded *display* names for the ``getWorksheets`` sync
    action, a different concern. This only needs to decide "is this the same column", tolerant of
    the kind of drift (casing, stray whitespace) that a human-maintained sheet header picks up
    over time; it never changes what's actually written to a cell.
    """
    return name.strip().casefold()


def _locate_key_columns(key_columns: list[str], header: list[str], header_owner: str) -> list[int]:
    """Return each of ``key_columns``'s 0-based index in ``header`` (:func:`_normalize_column_name`
    matched), or raise :class:`~client.exceptions.KeyColumnNotFoundError` naming the first missing
    one and which header (``header_owner`` — "the input table's header" or "the existing worksheet
    header") didn't have it.
    """
    normalized_header = [_normalize_column_name(cell) for cell in header]
    indices: list[int] = []
    for key_column in key_columns:
        normalized_key = _normalize_column_name(key_column)
        if normalized_key not in normalized_header:
            raise KeyColumnNotFoundError(
                f"Key column '{key_column}' not found in {header_owner}. Key columns must exist "
                "in both the input table's header and the existing worksheet header."
            )
        indices.append(normalized_header.index(normalized_key))
    return indices


def _build_key(row: list[str], indices: list[int]) -> str:
    """Build one composite lookup key from ``row``'s cells at ``indices`` (:data:`_KEY_SEPARATOR`
    joined). A short ``row`` (fewer cells than a given index) contributes ``""`` for that
    position, matching :func:`_prepare_row`'s own short-row padding.
    """
    return _KEY_SEPARATOR.join(row[index] if index < len(row) else "" for index in indices)


def _group_contiguous_runs(sorted_rows: list[int], max_size: int) -> Iterator[list[int]]:
    """Group ``sorted_rows`` (ascending, unique row numbers) into contiguous runs, each further
    split so no run exceeds ``max_size`` — one ``range`` PATCH per yielded run (:func:`_write_upsert`),
    so a batch of scattered updates costs one PATCH per contiguous block instead of one per row.
    """
    run: list[int] = []
    for row in sorted_rows:
        if run and row != run[-1] + 1:
            yield from _chunk(run, max_size)
            run = []
        run.append(row)
    if run:
        yield from _chunk(run, max_size)


def _chunk(run: list[int], max_size: int) -> Iterator[list[int]]:
    for start in range(0, len(run), max_size):
        yield run[start : start + max_size]


def _write_upsert(
    client: GraphClient,
    drive_id: str,
    file_id: str,
    worksheet_id: str,
    header: list[str],
    reader: Iterator[list[str]],
    key_columns: list[str],
    batch_size: int,
    is_new_sheet: bool,
    headers: dict[str, Any],
    session: str | None,
) -> None:
    """``write_mode='upsert'``: match CSV rows to existing sheet rows by ``key_columns``, PATCH
    only what actually changed, and append everything else.

    The whole CSV is read into memory (``data_rows``) — matching by key needs every row available
    up front, unlike ``overwrite``/``append``'s single streaming pass. This mirrors the
    memory/practicality trade-off already made for the existing side (see
    :data:`_UPSERT_MAX_EXISTING_CELLS`): upsert is meant for the kind of table an incremental sync
    naturally produces, not one so large that reading it twice is itself the bottleneck.

    An empty (never-written) sheet — including one just created for this run — has nothing to
    match against, so it behaves exactly like ``overwrite``: header + every row, written from A1.
    Otherwise: the existing ``usedRange`` is read once (``$select=address,text`` — ``text`` so
    every cell compares as the same kind of string the CSV itself parses into, avoiding a spurious
    "changed" on a cell Excel happens to store/render as a number; the address comes back in the
    same call, satisfying the "one GET" requirement without a second round trip for the header).
    """
    header_len = len(header)
    data_rows = [list(row) for row in reader]

    # Validated against the CSV header unconditionally, even for a brand-new/empty sheet that
    # will never actually match anything this run: a key column that doesn't exist in the input
    # table's own header is a configuration error regardless of the target sheet's state, and
    # catching it here (no network call needed — the header's already in memory) is cheaper than
    # only failing after a `usedRange` round trip a non-empty-sheet run would otherwise make.
    csv_key_indices = _locate_key_columns(key_columns, header, "the input table's header")

    if is_new_sheet:
        _write_full_rewrite(client, drive_id, file_id, worksheet_id, header, data_rows, header_len, batch_size, session)
        logger.info("Upsert: %d rows updated, %d appended, %d unchanged.", 0, len(data_rows), 0)
        return

    base_url = _worksheet_base_url(drive_id, file_id, worksheet_id)
    used_range = client.get(
        f"{base_url}/range/usedRange(valuesOnly=true)",
        params={"$select": "address,text"},
        headers=headers,
        retry_transient_workbook=True,
    ).json()
    range_info = parse_range_address(used_range["address"])
    cell_count = (range_info.end_row - range_info.start_row + 1) * (range_info.end_col - range_info.start_col + 1)
    if cell_count > _UPSERT_MAX_EXISTING_CELLS:
        raise UpsertRangeTooLargeError(
            f"The existing worksheet's used range is too large for write_mode 'upsert' "
            f"({cell_count} cells; the limit is {_UPSERT_MAX_EXISTING_CELLS}). Use write_mode "
            "'overwrite' or 'append' instead."
        )

    existing_rows: list[list[str]] = [[str(cell) for cell in row] for row in (used_range.get("text") or [])]
    if not existing_rows or not any(cell.strip() for cell in existing_rows[0]):
        logger.info("Sheet is empty.")
        _write_full_rewrite(client, drive_id, file_id, worksheet_id, header, data_rows, header_len, batch_size, session)
        logger.info("Upsert: %d rows updated, %d appended, %d unchanged.", 0, len(data_rows), 0)
        return

    existing_header = existing_rows[0]
    existing_data_rows = existing_rows[1:]

    existing_key_indices = _locate_key_columns(key_columns, existing_header, "the existing worksheet header")

    key_to_row: dict[str, tuple[int, list[str]]] = {}
    duplicate_seen = False
    for offset, existing_row in enumerate(existing_data_rows):
        row_number = range_info.start_row + 1 + offset
        key = _build_key(existing_row, existing_key_indices)
        if key in key_to_row:
            duplicate_seen = True
        key_to_row[key] = (row_number, existing_row)
    if duplicate_seen:
        logger.warning(
            "Duplicate key value(s) found among the existing worksheet's rows; using the last "
            "occurrence of each for matching."
        )

    updates: dict[int, list[str]] = {}
    appended_rows: list[list[str]] = []
    unchanged_count = 0
    for row in data_rows:
        padded = _prepare_row(row, header_len)
        key = _build_key(row, csv_key_indices)
        match = key_to_row.get(key)
        if match is None:
            appended_rows.append(padded)
            continue
        row_number, existing_row = match
        if _prepare_row(existing_row, header_len) == padded:
            unchanged_count += 1
            continue
        updates[row_number] = padded

    session_id = session
    for run in _group_contiguous_runs(sorted(updates), batch_size):
        batch = [updates[row_number] for row_number in run]
        session_id = _patch_batch(
            client, drive_id, file_id, worksheet_id, range_info.start_col, run[0], header_len, batch, session_id
        )

    append_start_row = range_info.end_row + 1
    for batch in _batched(iter(appended_rows), batch_size):
        session_id = _patch_batch(
            client, drive_id, file_id, worksheet_id, range_info.start_col, append_start_row, header_len, batch, session_id
        )
        append_start_row += len(batch)

    logger.info("Upsert: %d rows updated, %d appended, %d unchanged.", len(updates), len(appended_rows), unchanged_count)


def _write_full_rewrite(
    client: GraphClient,
    drive_id: str,
    file_id: str,
    worksheet_id: str,
    header: list[str],
    data_rows: list[list[str]],
    header_len: int,
    batch_size: int,
    session: str | None,
) -> str | None:
    """Write ``header`` + every one of ``data_rows`` from cell A1 (upsert's "nothing to match
    against yet" case — a brand-new or genuinely empty sheet behaves exactly like ``overwrite``).
    """
    session_id = session
    start_row = 1
    for batch in _batched(itertools.chain([header], data_rows), batch_size):
        padded_batch = [_prepare_row(row, header_len) for row in batch]
        session_id = _patch_batch(
            client, drive_id, file_id, worksheet_id, 1, start_row, header_len, padded_batch, session_id
        )
        start_row += len(padded_batch)
    return session_id
